/*
 * UAGUISetupAudit.java
 *
 * Created on May 13, 2005, 1:56 PM
 */

package steinbeck;

import java.io.File;

/**
 *
 * @author  Administrator
 */
public class UAGUISetupAudit extends javax.swing.JFrame {
    
    // this boolean determines if this window is opened
    // for a re-configuration (EDIT) or a new configuration (ADD)
    boolean isAddWindow;
    
    // we have two pieces of information to return UAAuditEntrance for script
    String scriptName;
    
    public String fileSeparator;
    
    String ip, port, username, remotePath, localPath;
    
    /** Creates new form UAGUISetupAudit */
    public UAGUISetupAudit() {
        initComponents();
        isAddWindow = true;
        scriptName = "";
        ip = "";
        port = "22";
        username = "root";
        remotePath = "/tmp/steinbeck";
        fileSeparator = "/";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Scan Configuration Window");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel1.setText("IP Address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 40, 80, 20);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel2.setText("Port");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 80, 20);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 80, 20);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 100, 20);

        jLabel5.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel5.setText("Remote Path");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 240, 100, 20);

        jTextField1.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jTextField1.setText("192.168.4.53");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 40, 110, 22);

        jTextField2.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jTextField2.setText("22");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 80, 110, 22);

        jTextField3.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jTextField3.setText("root");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 120, 110, 22);

        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(150, 160, 230, 23);

        jTextField5.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jTextField5.setText("/tmp/steinbeck");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 240, 230, 22);

        jButton1.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(80, 340, 80, 30);

        jButton2.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(320, 340, 80, 30);

        jLabel6.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel6.setText("Script");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 200, 100, 20);

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton3);
        jButton3.setBounds(390, 200, 30, 24);

        jTextField6.setBackground(new java.awt.Color(240, 235, 235));
        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(150, 200, 230, 22);

        jButton4.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton4);
        jButton4.setBounds(200, 340, 80, 30);

        jLabel7.setFont(new java.awt.Font("MS Sans Serif", 0, 14));
        jLabel7.setText("Local Path");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 280, 100, 20);

        jTextField7.setBackground(new java.awt.Color(240, 235, 235));
        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("MS Sans Serif", 0, 12));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(150, 280, 230, 22);

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton5);
        jButton5.setBounds(390, 280, 30, 24);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-476)/2, (screenSize.height-447)/2, 476, 447);
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        UAGUIEntrance.gui.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setLocalPath(new UAGUIFileChooser().getDirectory());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /** cancelling add audit job */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UAGUIEntrance.gui.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // auditscriptmanager window should open in mode 2
        UAGUIEntrance.gui.scriptManager.setMode(2);
        this.setVisible(false);
        UAGUIEntrance.gui.scriptManager.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    protected void setSelectedScript(String scriptFileName){
        fileSeparator = File.separator;
        setAuditor(scriptFileName);
    }
  
    protected void SetAddWindow(){
        isAddWindow = true;
        fillOutFields();
    }
    
    private void fillOutFields(){
        setIP(ip);
        setPort(port);
        setUsername(username);
        setRemotePath(remotePath);
        setLocalPath(localPath);
        setPassword("");
        if((scriptName.compareTo("") != 0) && (fileSeparator.compareTo("") != 0))
            setAuditor(scriptName);
    }
    
    protected void SetEditWindow(){
        isAddWindow = false;
    }
    
    /** performing add audit or edit audit job */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                
        // first check if everything is filled!!
        if(!checkFields()){
            UAGUIEntrance.gui.showErrorMessage("Fill all the inputs (except maybe password)");
            return;
        }
        
        // first test the connection 
        if(!UAGUIEntrance.gui.testConnection()){
            return;
        }
        
        this.setVisible(false);

        if(isAddWindow)
            UAGUIEntrance.gui.addAudit();
        else
            UAGUIEntrance.gui.editAudit();

        UAGUIEntrance.gui.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private boolean checkFields(){
        if(         getIP().compareTo("") == 0
                ||  getPort().compareTo("") == 0
                ||  getUsername().compareTo("") == 0
                ||  getLocalPath().compareTo("") == 0
                ||  getRemotePath().compareTo("") == 0
                ||  getScriptName().compareTo("") == 0)
            return false;
        
        ip = getIP();
        username= getUsername();
        port = getPort();
        remotePath = getRemotePath();
        localPath = getLocalPath();
        return true;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("22");
        jTextField3.setText("root");
        jPasswordField1.setText("");
        jTextField5.setText("/tmp/steinbeck");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    protected String getIP(){return jTextField1.getText();}
    protected String getPort(){return jTextField2.getText();}
    protected String getUsername(){return jTextField3.getText();}
    protected String getPassword(){
        char password [] = jPasswordField1.getPassword();        
        return new String(password);
    }
    protected String getRemotePath(){return jTextField5.getText();}
    protected String getLocalPath(){return jTextField7.getText();}
    protected String getScriptName(){return scriptName;}
    protected String getAuditor(){return scriptName;}

    protected void setIP(String IP){jTextField1.setText(IP);}
    protected void setPort(String port){jTextField2.setText(port);}
    protected void setUsername(String username){jTextField3.setText(username);}
    protected void setPassword(String localPath){jPasswordField1.setText(localPath);}
    protected void setRemotePath(String remotePath){jTextField5.setText(remotePath);}
    protected void setLocalPath(String localPath){jTextField7.setText(localPath);}
    protected void setAuditor(String auditor){
        jTextField6.setText(auditor);
        scriptName = auditor;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
    
}
